##################################################################################################
# Status service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: status-svc
  labels:
    app: status-svc
    service: status-svc
spec:
  ports:
  - name: http
    protocol: TCP
    port: 9083
    targetPort: 9083
  - name: exporter
    protocol: TCP
    port: 9095
    targetPort: 9095
  selector:
    app: status-svc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ctibco-status-svc
  labels:
    account: status-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-svc
  labels:
    app: status-svc
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-svc
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: status-svc
        version: v1
    spec:
      serviceAccountName: ctibco-status-svc
      containers:
      - env:
        - name: STATUS_MY_PORT
          value: "9082"
        - name: PROM_MON_PORT
          value: "9095"
        - name: BW_PROFILE
          value: "docker"
        - name: BW_LOGLEVEL
          value: "ERROR" 
        - name: BW_PROMETHEUS_ENABLE
          value: "true"
        image: docker.io/u3132/statappmon:2.0.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: 500Mi
            cpu: 500m
          limits:
            memory: 900Mi
            cpu: 1000m
        name: status-svc
        ports:
        - containerPort: 9083
        - containerPort: 9095